# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.docker/build-push-action
                      - name: Docker build and push
  # You may pin to the exact commit or the version.
  # uses: cloudposse/github-action-docker-build-push@51728c18e98e68a3365054e724b186912d8cbe16
  uses: cloudposse/github-action-docker-build-push@1.16.0
  with:
    # List of extra privileged entitlement (e.g., network.host,security.insecure)
    allow: # optional
    # Set the networking mode for the RUN instructions during build
    network: # optional
    # BuildKit daemon flags
    buildkitd-flags: # optional, default is --allow-insecure-entitlement security.insecure --allow-insecure-entitlement network.host
    # List of additional driver-specific options. (eg. image=moby/buildkit:master)
    driver-opts: # optional
    # Working directory
    workdir: # optional, default is ./
    # Dockerfile name
    file: # optional, default is Dockerfile
    # List of build-time variables
    build-args: # optional
    # Organization
    organization: 
    # Repository
    repository: 
    # Docker registry
    registry: 
    # Sets the target stage to build
    target: # optional, default is 
    # List of target platforms for build (e.g. linux/amd64,linux/arm64,linux/riscv64,linux/ppc64le,linux/s390x,etc)
    platforms: # optional, default is linux/amd64
    # Generate provenance attestation for the build
    provenance: # optional
    # Image name (excluding registry). Defaults to {{$organization/$repository}}.
    image_name: # optional, default is 
    # Docker login
    login: # optional, default is 
    # Docker password
    password: # optional, default is 
    # List of external cache sources for buildx (e.g., user/app:cache, type=local,src=path/to/dir)
    cache-from: # optional, default is type=gha
    # List of cache export destinations for buildx (e.g., user/app:cache, type=local,dest=path/to/dir)
    cache-to: # optional, default is type=gha,mode=max
    # Send the --no-cache flag to the docker build process
    no-cache: # optional, default is false
    # List of SSH agent socket or keys to expose to the build
    ssh: # optional
    # List of tags (supports https://github.com/docker/metadata-action#tags-input)
    tags: # optional
    # List of secrets to expose to the build (e.g., key=string, GIT_AUTH_TOKEN=mytoken)
    secrets: # optional
    # List of secret files to expose to the build (e.g., key=filename, MY_SECRET=./secret.txt)
    secret-files: # optional
    # Set to `true` to tag images with the PR HEAD SHA instead of the merge commit SHA within pull requests.
    docker-metadata-pr-head-sha: # optional, default is false
    # Enable debug mode
    debug: # optional, default is false
          
